main.py

20250212 Main

---

.gitignore
dashboard/__init__.py
dashboard/routes/static.py
dashboard/static/css/base_style.css
dashboard/static/css/header.css
dashboard/templates/index.html
dashboard/templates/partials/footer.html
dashboard/templates/partials/head_script.html
dashboard/templates/partials/header.html
package-lock.json
package.json

[20250218 header footer](https://github.com/JA2PYC/ja2pyc_study_llama/commit/718757194e7d68a82dbcd00f1a702f8f58c0b892)

20250218 header footer

---

dashboard/static/css/footer.css
dashboard/templates/partials/footer.html

Set footer

---

dashboard/static/css/footer.css
dashboard/static/css/header.css
dashboard/templates/partials/footer.html

Footer Copyright

---

dashboard/static/css/aside.css
dashboard/static/css/index.css
dashboard/templates/index.html

Set Index Page

---

dashboard/static/css/aside.css
dashboard/static/js/index.js

20250225 index.js

---

api/ollama_api.py
api/openai_api.py
dashboard/static/js/index.js

Set Ollama API

---

main.py

20250306 Process

---

main.py

20250307 Cleanup

---

models/ollama.py

20250312 pip install ollama

---

models/ollama.py
test.py

20250313 set ollama binary

---

models/ollama.py

20250314 check ollama

---

main.py
models/ollama.py

20250315 ollama process port

---

main.py
models/ollama.py
test.py

[20250316 check ollama](https://github.com/JA2PYC/ja2pyc_study_llama/commit/77c9f39f6aaa7fe2d043d23ed39b10a57afcb10c)

20250316 check ollama

---

models/ollama.py

20250319 Ollama return

---

database/db_instance.py

20250321 db instance

---

database/db_instance.py

20250322 db

---

database/db_instance.py

20250323 init db

---

dashboard/templates/admin/dashboard.html

20250324 admin page

---

database/db_instance.py

20250325 conn commit

---

logging/logger.py

20250326 logger

---

logger/logger.py
main.py

20250327 path dirname

---

logger/logger.py

20250404 Logger singletone

---

logger/logger.py
test.py

20250404 Project Root

---

config/paths.py
test.py

20250413 test sys.path & os.getcwd

20250413 test sys.path & os.getcwd

---

config/testmodule.py
test.py

20250414 test module

---

config/testmodule.py

20250415 test __file__ sys.path module

20250415 test __file__ sys.path module

---

config/db_settings.py
config/models.py
config/settings.py

20250419 settings

---

config/init_db.py

20250420 init config db

---

dashboard/routes/home.py

20250424 celery delay

---

dashboard/routes/home.py
dashboard/tasks/test_task.py

20250425 hint

---

database/db_config.py

20250428 db module config

---

database/__init__.py
database/db_connector.py
database/db_init.py
database/db_status.py

20250429 db_client module

---

main_test.py

20250502 test mock

---

database/__init__.py
database/connector.py
database/init_db.py

20250513 engine

---

database/connector.py
database/init_db.py
run.py

[20250514 engine](https://github.com/JA2PYC/ja2pyc_study_llama/commit/08e13492d0a8ad76ba55b49f683548c72202efd5)

20250514 engine

---

database/__init__.py
database/connector.py
database/entities/base.py
database/entities/user_entity.py
database/init_db.py

[20250515 entity base](https://github.com/JA2PYC/ja2pyc_study_llama/commit/a437aa8b6a39eb2a86c7706757558a2143422502)

20250515 entity base

---

database/entities/base.py
database/init_db.py

20250516 base

---

database/entities/user_entity.py
database/repositories/user_repository.py

20250521 modify user entity

---

database/__init__.py
database/database_client.py
database/entities/__init__.py
database/init_db.py
database/init_entities.py

20250523 entity module

---

auth/auth_service.py
auth/jwt_token.py
auth/password_hasher.py
dashboard/routes/auth_routes.py
database/__init__.py
database/entities/__init__.py
database/init_entities.py

20250525 auth

---

auth/utils.py

20250527 hash
